name: ripgrep ARMv7a Static Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Compile
      run: |
        docker run --rm --privileged -v ${{ github.workspace }}:/workspace -w /workspace termux/termux-docker:arm /bin/sh -c "
          export DEBIAN_FRONTEND=noninteractive
          pkg update -y &&
          pkg upgrade -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' &&
          pkg install -y git rust binutils &&
          cd /tmp &&
          git clone https://github.com/BurntSushi/ripgrep &&
          cd ripgrep &&
          cargo build --release &&
          strip target/release/rg &&
          cp target/release/rg /workspace/rg-static-armv7
        "

    - name: Artifact
      uses: actions/upload-artifact@v7
      with:
        name: rg-static-armv7
        path: rg-static-armv7
