name: Android ARMv7a Static Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Compile
      run: |
        docker run --rm --privileged -v ${{ github.workspace }}:/workspace -w /workspace termux/termux-docker:arm /bin/sh -c "
          export DEBIAN_FRONTEND=noninteractive
          pkg update -y &&
          pkg upgrade -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' &&
          pkg install -y git automake autoconf ncurses-utils ncurses clang make libcurl &&
          cd /tmp &&
          git clone https://github.com/Ilan12346-maya/htop source &&
          cd source &&
          ./autogen.sh &&
          ./configure --enable-static --disable-unicode LDFLAGS='-static' &&
          make -j$(nproc) &&
          cp htop /workspace/htop-static-armv7
        "

    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: htop-static-armv7
        path: htop-static-armv7
