---
name: Build Librespeed CLI (Alpine Edition)
on:
  workflow_dispatch: null
jobs:
  build-librespeed:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Install System Dependencies
        run: |
          apk update
          apk add git go bash build-base doas
      - name: Clone and Build Librespeed-CLI
        run: |
          git clone https://github.com/librespeed/speedtest-cli
          cd speedtest-cli

          chmod +x build.sh
          ./build.sh

          ls -R out/
      - name: Upload Librespeed Binary
        uses: actions/upload-artifact@v7
        with:
          name: librespeed-cli-alpine
          path: speedtest-cli/out/librespeed-cli-*
