name: Compile PCManFM & LibFM (GTK2) Full Bundle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest

    steps:
    - name: Install Build Dependencies
      run: |
        apk update
        apk add --no-cache \
          build-base git automake autoconf libtool intltool \
          gtk+2.0-dev polkit-dev glib-dev menu-cache-dev \
          libexif-dev libx11-dev vala gettext-dev \
          libfm-extra-dev gtk-doc libxml2-utils \
          dbus-gl-dev dbus-dev libxml2-dev

    - name: Clone Repositories
      run: |
        git clone --depth 1 https://github.com/lxde/libfm.git
        git clone --depth 1 https://github.com/lxde/pcmanfm.git

    - name: Build LibFM
      run: |
        cd libfm
        ./autogen.sh
        ./configure \
          --prefix=/usr \
          --sysconfdir=/etc \
          --with-gtk=2 \
          --enable-udisks \
          --disable-static \
          --disable-gtk-doc 
        make -j$(nproc)
        make install DESTDIR=$(pwd)/../export

    - name: Build PCManFM
      run: |
        # Inyectar la libfm reci√©n compilada
        export PKG_CONFIG_PATH=$(pwd)/export/usr/lib/pkgconfig:$PKG_CONFIG_PATH
        export C_INCLUDE_PATH=$(pwd)/export/usr/include:$C_INCLUDE_PATH
        export LIBRARY_PATH=$(pwd)/export/usr/lib:$LIBRARY_PATH
        
        cd pcmanfm
        ./autogen.sh
        ./configure \
          --prefix=/usr \
          --sysconfdir=/etc \
          --with-gtk=2
        make -j$(nproc)
        make install DESTDIR=$(pwd)/../export

    - name: Upload Full Bundle
      uses: actions/upload-artifact@v4
      with:
        name: pcmanfm-gtk2-full-alpine
        path: export/
