name: Build Tuta Mail Desktop for Alpine Stable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: alpine:latest
      options: --user root

    steps:
    - name: Install Build Tools
      run: |
        apk update
        apk add --no-cache \
          build-base git nodejs npm rust cargo python3 \
          bash libsecret-dev dbus-dev pkgconfig \
          libx11-dev libxkbfile-dev make g++ py3-setuptools

    - name: Install EMSDK
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install 3.1.59
        ./emsdk activate 3.1.59

    - name: Clone and Setup Tuta
      run: |
        git clone https://github.com/tutao/tutanota.git
        cd tutanota
        LATEST_TAG=$(git tag -l "tutanota-release-*" | sort -V | tail -n1)
        git checkout $LATEST_TAG
        git submodule update --init --recursive
        npm ci

    - name: Build Desktop
      run: |
        cd tutanota
        # Cargar entorno emscripten e iniciar build
        source ../emsdk/emsdk_env.sh
        npm run build-packages
        rm -rf libs/webassembly/include
        node desktop --custom-desktop-release --unpacked

    - name: Prepare Export
      run: |
        mkdir -p export
        cp -r tutanota/build/desktop/* export/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tuta-desktop-alpine
        path: export/
