---
name: Build Zathura and zathura-pdf-mupdf for Debian 12
on:
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:12
    steps:
      - name: Update and install dependencies
        run: |
          apt-get update -y
          apt-get install -y --no-install-recommends \
            build-essential \
            meson \
            ninja-build \
            git \
            curl \
            ca-certificates \
            libgirara-dev \
            libsqlite3-dev \
            desktop-file-utils \
            file \
            libsynctex-dev \
            libseccomp-dev \
            appstream \
            python3-sphinx \
            texlive-binaries \
            libappstream-dev \
            check \
            xvfb \
            weston \
            libcairo2-dev \
            libgumbo-dev \
            libjbig2dec0-dev \
            libjpeg62-turbo-dev \
            libmupdf-dev \
            libopenjp2-7-dev \
            libssl-dev
      - name: Create build directory
        run: mkdir /build-dir
      - name: Download and build Zathura
        working-directory: /build-dir
        run: >
          curl -L -O https://github.com/pwmt/zathura/archive/refs/tags/0.5.14.tar.gz

          tar xzf 0.5.14.tar.gz

          cd zathura-0.5.14

          meson setup build --prefix=/usr

          ninja -C build

          xvfb-run ninja -C build test

          mkdir /artifacts

          DESTDIR=/artifacts ninja -C build install
      - name: Download and build zathura-pdf-mupdf
        working-directory: /build-dir
        run: >
          curl -L -O
          https://github.com/pwmt/zathura-pdf-mupdf/archive/refs/tags/0.4.6.tar.gz

          tar xzf 0.4.6.tar.gz

          cd zathura-pdf-mupdf-0.4.6

          cat > 0001-Remove-mupdf-linking-detection.patch << EOF

          From e91e5ad64d20eb4a7df377effc12ec21ba6f5f7c Mon Sep 17 00:00:00 2001

          From: =?UTF-8?q?Johannes=20L=C3=B6thberg?= <johannes@kyriasis.com>

          Date: Fri, 18 Mar 2022 00:02:43 +0100

          Subject: [PATCH] Remove mupdf linking detection


          MIME-Version: 1.0

          Content-Type: text/plain; charset=UTF-8

          Content-Transfer-Encoding: 8bit


          Signed-off-by: Johannes LÃ¶thberg <johannes@kyriasis.com>

          ---
           meson.build | 40 ++++++++++++++--------------------------
           1 file changed, 14 insertions(+), 26 deletions(-)

          diff --git a/meson.build b/meson.build

          index e582e06..2c6fd87 100644

          --- a/meson.build

          +++ b/meson.build

          @@ -23,7 +23,6 @@ zathura = dependency('zathura', version: '>=0.5.2')
           girara = dependency('girara-gtk3')
           glib = dependency('glib-2.0')
           cairo = dependency('cairo')
          -mupdf = dependency('mupdf', required: false, version: '>=@0@.@1@'.format(mupdf_required_version_major, mupdf_required_version_minor))

           build_dependencies = [
             zathura,
          @@ -32,26 +31,20 @@ build_dependencies = [
             cairo,
           ]

          -if not mupdf.found()

          - # normal build of mupdf

          - mupdf = cc.find_library('mupdf', has_headers: ['mupdf/fitz/version.h', 'mupdf/fitz.h', 'mupdf/pdf.h'], required: true)

          - mupdfthird = cc.find_library('mupdf-third')

          - version_check = '''

          -#include <mupdf/fitz/version.h>

          +mupdf = cc.find_library('mupdf')


          -#if FZ_VERSION_MAJOR < @0@ || (FZ_VERSION_MAJOR == @0@ && FZ_VERSION_MINOR < @1@)

          -#error "mupdf @0@.@1@ or newer is requried"

          -#endif

          -'''.format(mupdf_required_version_major, mupdf_required_version_minor)

          - if not cc.compiles(version_check, dependencies: [mupdf])

          -   error('mupdf @0@.@1@ or newer is required'.format(mupdf_required_version_major, mupdf_required_version_minor))

          - endif

          +libjpeg = dependency('libjpeg')

          +libjbig2dec = cc.find_library('jbig2dec')

          +libopenjp2 = dependency('libopenjp2')

          +gumbo = dependency('gumbo')


          - build_dependencies += [mupdf, mupdfthird]

          -else

          - # build from Debian's libmupdf-dev

          - build_dependencies += [mupdf]

          -endif

          +build_dependencies += [

          +  mupdf,

          +  libjpeg,

          +  libjbig2dec,

          +  libopenjp2,

          +  gumbo,

          +]

           if get_option('plugindir') == ''
             plugindir = zathura.get_variable(pkgconfig: 'plugindir')
          EOF

          patch -p1 < 0001-Remove-mupdf-linking-detection.patch

          export PKG_CONFIG_PATH=/artifacts/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH

          meson setup build --prefix=/usr

          ninja -C build

          DESTDIR=/artifacts ninja -C build install
      - name: Package artifacts
        working-directory: /artifacts
        run: tar czf /zathura-build.tar.gz .
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zathura-build
          path: /zathura-build.tar.gz
